.PHONY: clean All

All:
	@echo "----------Building project:[ RealGui - Debug ]----------"
	@cd "RealGui2.0" && "$(MAKE)" -f  "RealGui.mk"
clean:
	@echo "----------Cleaning project:[ RealGui - Debug ]----------"
	@cd "RealGui2.0" && "$(MAKE)" -f  "RealGui.mk" clean
